version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.14
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: webpack
    versions:
    - 2.7.0
